In [69]:
import pandas as pd
from sklearn.model_selection import train_test_split
from category_encoders import TargetEncoder

In [70]:
pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (2.10.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (2.4.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (3.0.2)
Requirement already satisfied: patsy>=0.5.1 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (1.18.0)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (2.20.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\anushka saha\appdata\local\programs\python\python314\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (26.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

#### CREATE A DATAFRAME WITH 3 COLS AND 10 ROWS FOR TARGET ENCODER ,LAST COL MUST CONTAIN MULTICLASS LABELS

##### SCENARIO 1

In [71]:
df = pd.DataFrame({
    'cat_col1':['A','B','A','C','B','A','C','B','A','C'],
    'cat_col2':['X','Y','X','Z','Y','X','Z','Y','X','Z'],
    'label':    ['class0','class1','class2','class0','class1','class2','class0','class1','class2','class0']
})

In [72]:
x= df.drop(columns='label')
y=df['label']

In [73]:
xtrain, xtest, ytrain, ytest = train_test_split(
    x,
    y,
    train_size=0.8,
    random_state=42
)

In [74]:
'''
data = {
    'cat_col1':['A','B','A','C','B','A','C','B','A','C'],
    'cat_col2':['X','Y','X','Z','Y','X','Z','Y','X','Z'],
    'numerical':[10,25,15,30,20,12,28,22,18,35]
}
df = pd.DataFrame(data)
x= df.drop(columns='numerical')
y=df['numerical']
xtrain, xtest, ytrain, ytest = train_test_split(
    x,
    y,
    train_size=0.8,
    random_state=42
)
'''

"\ndata = {\n    'cat_col1':['A','B','A','C','B','A','C','B','A','C'],\n    'cat_col2':['X','Y','X','Z','Y','X','Z','Y','X','Z'],\n    'numerical':[10,25,15,30,20,12,28,22,18,35]\n}\ndf = pd.DataFrame(data)\nx= df.drop(columns='numerical')\ny=df['numerical']\nxtrain, xtest, ytrain, ytest = train_test_split(\n    x,\n    y,\n    train_size=0.8,\n    random_state=42\n)\n"

In [75]:
xtrain

  cat_col1 cat_col2
5        A        X
0        A        X
7        B        Y
2        A        X
9        C        Z
4        B        Y
3        C        Z
6        C        Z

In [76]:
x['cat_col1'].value_counts()

cat_col1
A    4
B    3
C    3
Name: count, dtype: int64

In [77]:
ytrain

5    class2
0    class0
7    class1
2    class2
9    class0
4    class1
3    class0
6    class0
Name: label, dtype: str

In [78]:
encoder = TargetEncoder()
encoder.fit_transform(xtrain,ytrain)

   cat_col1  cat_col2
5  0.840105  0.840105
0  0.840105  0.840105
7  0.785463  0.785463
2  0.840105  0.840105
9  0.634151  0.634151
4  0.785463  0.785463
3  0.634151  0.634151
6  0.634151  0.634151

In [79]:
encoder.transform(xtest,ytest)

   cat_col1  cat_col2
8  0.840105  0.840105
1  0.785463  0.785463

In [80]:
encoder.transform(xtest)

   cat_col1  cat_col2
8  0.840105  0.840105
1  0.785463  0.785463

In [81]:
encoder = TargetEncoder()
encoder.fit_transform(xtrain['cat_col1'],ytrain)

   cat_col1
5  0.840105
0  0.840105
7  0.785463
2  0.840105
9  0.634151
4  0.785463
3  0.634151
6  0.634151

In [82]:
encoder = TargetEncoder(cols = ['cat_col1'],handle_unknown='value')
encoder.fit_transform(xtrain,ytrain)

   cat_col1 cat_col2
5  0.840105        X
0  0.840105        X
7  0.785463        Y
2  0.840105        X
9  0.634151        Z
4  0.785463        Y
3  0.634151        Z
6  0.634151        Z

In [83]:
encoder.transform(xtest)

   cat_col1 cat_col2
8  0.840105        X
1  0.785463        Y